version: "3"
services:
  krakend:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  grafana:
    build:
      context: ./gateway/monitoring/grafana
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
  influxdb:
    build:
      context: ./gateway/db
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
