version: "3"
services:
  krakend:
    image: jordywalraven/ciri2-gateway:latest
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - AUDIENCE=${AUDIENCE}
      - JWK_URL=${JWK_URL}
      - COMPONENT_HOST=${COMPONENT_HOST}
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_PORT=${INFLUXDB_PORT}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
  grafana:
    image: jordywalraven/ciri2-grafana:latest
    build:
      context: ./gateway/monitoring/grafana
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    environment:
      - INFLUXDB_HOST=${INFLUXDB_HOST}
      - INFLUXDB_PORT=${INFLUXDB_PORT}
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
      
  influxdb:
    image: influxdb:1.8.10
    environment:
      - INFLUXDB_DB=krakend
      - INFLUXDB_USER=${INFLUXDB_USER}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    ports:
      - "8086:8086"
