name: Release


on:
  release:
    types: [published]
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push KrakenD-Gateway
        uses: docker/build-push-action@v5
        with:
          context: ./gateway
          push: true
          tags: |
            jordywalraven/ciri2-gateway:latest
            jordywalraven/ciri2-gateway:${{ github.sha }}
      - name: Build and push Grafana
        uses: docker/build-push-action@v5
        with:
          context: ./gateway/grafana
          push: true
          tags: |
            jordywalraven/ciri2-grafana:latest
            jordywalraven/ciri2-grafana:${{ github.sha }}